* 4chan browser for Emacs

** Installation

First, for images to work you need a build of Emacs that supports
Imagemagick. You can skip this if you are too lazy, and the browser
should still work except that images won't be displayed. Install
Imagemagick, and build Emacs from source with the ~--with-imagemagick~
option during the ~./configure~ step. You can get Emacs source [[http://ftpmirror.gnu.org/emacs/][here]] or
from the git repo [[https://savannah.gnu.org/projects/emacs/][here]]. In short, what you need to run is ~./configre
--with-imagemagick && make && make install~. If you downloaded it from
the repo, run ~./autogen.sh~ before ~./configure~.

In your .emacs.d/lisp or wherever you keep your elisp, clone this
repo:

#+begin_src
git clone https://github.com/yyyuuuuu/chan.git
#+end_src

Put the repo on your load path and load ~chan~. If you use use-pacakge
and cloned the repos files in .emacs.d/lisp, then its:
#+begin_src elisp
(use-package chan
  :after (recaptcha-v2)
  :load-path "lisp/chan")
#+end_src

In vanilla emacs its:
#+begin_src elisp
(add-to-list 'load-path "~/.emacs.d/lisp/chan/")
(require 'chan)
#+end_src

** Usage

~M-x chan-catalog~ to get started. (Don't worry about there being no
images; images are disabled in the catalog for now)

Keys:
| Enter                                    | If point is on a thread in catalog, visit thread under point        |
| r                                        | Write reply to thread in buffer, or create new thread if at catalog |
| Space                                    | Scroll up                                                           |
| Backspace                                | Scroll down                                                         |
| n                                        | Next post                                                           |
| p                                        | Prev post                                                           |
| l                                        | Center viewport on point                                            |
| <,>                                      | Move to beginning/end of buffer                                     |
| Enter (when over backlink such as >>751) | Jump to linked post                                                 |
| ,                                        | Jump back to last backlinked followed                               |

Keys in a post authoring buffer:
| C-Enter | Submit post (takes you to a recaptcha) |
| C-c C-o | Attach a file                          |

In the recaptcha buffer, press Enter to submit the captcha and your
post. Select images with these keys:
| u | i | o |
| j | k | l |
| m | , | . |

To abandon posting or a recaptcha early, just C-x k kill the buffers.

** Other notes

This browser is currently not in a very usable state and is rather
barebones. chan.el is only 900 lines. You can browse and post to \/g\/
with it, but it will be very awkward compared to a web browser. It is
hardcoded to only browse \/g\/ right now. Image loading is slow and
unoptimized, so they are disabled in the catalog. Many features like
backlinks and image viewing are missing. If posting encounters an
error like an incorrect captcha, it won't handle it gracefully.
